config/routes.rb
BookmarksProject::Application.routes.draw do

    resources :sessions, :only => [:new, :create, :destroy]
    resources :users
    resources :bookmarks

  root :to => 'sessions#new'
  
  match '/signin', :to => 'sessions#new' #signin_path
  match '/signout', :to => 'sessions#destroy', :via => :delete #signout_path
  
  match '/index',     :to => 'users#index'
  match '/show',      :to => 'users#show'
  match '/signup',    :to => 'users#new'  #signup_path
  match '/edit',      :to => 'users#edit'
  match '/help',      :to => 'users#help'
  
  
  match '/show',  :to => 'bookmarks#show' #bookmark_path(@user_id)
  match '/index', :to => 'bookmarks#index' #bookmarks_path
  
  match  ':bookmarks/:new/@current_user', :to => 'bookmarks#new' #new_bookmark_path

end 
  

app/models/bookmark.rb
# == Schema Information
#
# Table name: bookmarks
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  url        :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Bookmark < ActiveRecord::Base
    belongs_to :user
    
    attr_accessible :name, :url
  
    validates :name, :url, :presence => true,
                    :length =>  { :maximum => 100 }
    validates :url, :presence => true,
                    :length => { :minimum => 10}
                    
    validates :user_id, :presence => true
                     
    default_scope :order => "bookmarks.created_at DESC"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  username           :string(255)
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

class User < ActiveRecord::Base
  has_many :bookmarks
  
  attr_accessor :password
  
  attr_accessible :username, :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  
  validates :username, :presence => true,
            :uniqueness => { :case_sensitive => false },
            :length => {:maximum =>100}
  validates :name, :presence => true,
            :length => { :within => 2..75 }
  validates :email, :presence => true,
            :format => { :with => email_regex }
  validates :password, :presence => true,
            :confirmation => true,
            :length => { :within => 7..40 }
  
  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  def feed
     Bookmark.where("user_id = ?")
  end

  class << self
    def User.authenticate(email, submitted_password)
      user = find_by_email(email)
      return nil  if user.nil?
      return user if user.has_password?(submitted_password)
    end
    def User.authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    before_filter :authenticate
    before_filter :authorized_user, :only => :destroy
  
  caches_action :layout => false
  
  def index
    @bookmarks = Bookmark.all
    @title = "Bookmarks"
  end

  def show
    @bookmark = Bookmark.find(params[:id])
    @title = @bookmark.name
  end

  def new
    @bookmark = Bookmark.new
    @title = "New Bookmark"
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
    @title = "Edit Bookmarks"
  end

  def create
    @bookmark = current_user.bookmarks.build(params[:bookmark])
    if @bookmark.save
          redirect_to @current_user, :flash => {:success => "Bookmark created!"}
    else
      render "users/show"
    end
  end

  def update
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to(@bookmark, :notice => 'Bookmark was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bookmark.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to current_user, :flash => {:success => "Bookmark deleted!"}
    end

   private
        def authorized_user
            @bookmark = Bookmark.find(params[:id])
            redirect_to root_path unless current_user?(@bookmark.user)
        end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
      @title = "Sign in"
    end

    def create
      user = User.authenticate(params[:session][:email],
                               params[:session][:password])
      
      if user.nil?
        flash.now[:error] = 'Invalid email/password combination.'
        @title = "Sign in"
        render 'new'
      else
        sign_in user
        redirect_back_or user
      end
    end

    def destroy
      sign_out
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    before_filter :authenticate,  :only => [:index, :edit, :update, :destroy]
    before_filter :correct_user,  :only => [:edit, :update]
    before_filter :admin_user,    :only => :destroy
    
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @title = @user.username
    if signed_in?
      @bookmarks = @user.bookmarks.paginate(:page => params[:page])
      @bookmark = Bookmark.new
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
    unless signed_in?
      redirect_to signin_path
    end
  end

  def new
    @title = "Sign up"
    @user = User.new
  end

  def edit
    @title = 'Profile'
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to pal.atab.le!"
      redirect_to @user
    else
      @title = "Sign up"
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      :flash[:success] = "Profile updated." 
      redirect_to @user
    else
      @title = "Profile"
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  def help
    @title = "Help"
  end
  
  private

  def correct_user
    @user =User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  
  def admin_user
    @user =User.find(params[:id])
    redirect_to(root_path) unless (!current_user.admin? || current_user?(user))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #put the user id into the cookie
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
  #setter
  def current_user=(user)
    @current_user = user
  end
  #getter - short circuit evaluation. if it is not set, set it, if it is set use it.
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
   def authenticate
      deny_access unless signed_in?
  end
  
  private
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def clear_return_to
    session[:return_to] = nil
  end
  
  def user_from_remember_token
   User.authenticate_with_salt(*remember_token)
  end
  
  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_bookmark.html.erb
<tr>
    <td class="bookmark">
        <div class="content">
            URL : <a href="<%= bookmark.url %>" target=_blank ><%= bookmark.url %></a>
        </div>
        <div class="content">
            Name: <%= bookmark.name %>
        </div>
        <span class="timestamp">
           Posted <strong><i><%= bookmark.created_at %></i></strong> ago.
        </span>
    </td>
        <% user = bookmark.user rescue User.find(bookmark.user_id)%>
        <% if current_user?(user) %>
    <td>
            <%= link_to "delete", bookmark, :method => :delete,
                                                        :confirmation => "You sure",
                                                        :title => bookmark.name %>
    </td>
        <% end %>
</tr>

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %>
        prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <input type="hidden" name="bookmark_user_id" value="<%= @bookmark.user_id %>">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th>User Id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookmarks.each do |bookmark| %>
  <tr>
    <td><%= bookmark.name %></td>
    <td><%= link_to bookmark.url, bookmark.url %></td>
    <td><%= bookmark.user_id %></td>
    <td><%= link_to 'Show', bookmark %></td>
    <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
    <td><%= link_to 'Destroy', bookmark, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<!--%= link_to 'Back', bookmarks_path %-->
<%= link_to 'Back', :back %>
<%= render 'form' %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bookmark.name %>
</p>

<p>
  <b>Url:</b>
  <%= @bookmark.url %>
</p>
<p>
  <b>Id:</b>
  <%= @bookmark.user_id %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', :back %>

app/views/layouts/_footer.html.erb
<footer>
  <div id="footer">
    <nav><ul>
          <% if signed_in? %>
            <li><%= link_to "Home", user_path(current_user) %></li>
            <li><%= link_to "Profile", edit_user_path(current_user)%></li>
            <li><%= link_to "Logout", signout_path, :method => :delete %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Search...", '#' %></li>
          <% else %>
              <li><%= link_to "Sign Up", signup_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "Search...", '#' %></li>
          <% end %>
    </ul></nav>
    <div class="block">
      <p>Copyright &copy; <%= Time.now.year %> Web App.</p>
     </div>      
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div id="header">
      <h1><%= link_to "pal.atab.le", root_path %></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <% if signed_in? %>
            <li><%= link_to "Home", current_user%></li>
            <li><%= link_to "Profile", edit_user_path(current_user) %></li>
            <li><%= link_to "Logout", signout_path, :method => :delete %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Search...", '#' %></li>
          <% else %>
              <li><%= link_to "Sign Up", signup_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "Search...", '#' %></li>
          <% end %>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div> 
</header>

app/views/layouts/_stylesheets.html.erb
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => false %>
  <%= javascript_include_tag :defaults, :cache => false %>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>pal.atab.le | <%= @title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <%= render 'layouts/header' %>   
    <div id="wrapper" class="wat-cf">
    <div class="flash">
      <% flash.each do |type, message| -%>
      <div class="message <%= type %>">
        <p><%= message %></p>
      </div>
      <% end -%>
    </div>
       <div id="main">
        <%= yield %>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id='error_explanation'>
    <div class="alert alert-error">
      <h2><%= pluralize(@user.errors.count, 'error') %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:
      </h2>
    </div>  
    <p>There were problems with the following fields:</p>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
           <li> <%= msg %> </li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/users/_fields.html.erb
  <%= render 'shared/error_messages', :object => f.object %>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
      <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
    </div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/users/_user.html.erb
 <li>
    <%= link_to user.username, user %>
    
    <% if current_user.admin? %>
    | <%= link_to "delete", user, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{user.name}" %>
    <% end %>
  </li>

app/views/users/edit.html.erb
<h1>Edit User Profile</h1>
<%= render 'form' %>
<%= link_to 'Cancel', @user %>

app/views/users/help.html.erb
  <h1>Help</h1>
  <p>
    Get help on Ruby on Rails Tutorial at the
    <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
    To get help on this sample app, see the
    <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
  </p>

app/views/users/index.html.erb
<h1>All Users</h1>
<%= will_paginate %>
<ul class='users'>
  <% @users.each do |user| %>
    <%= render @users %>
 <% end %>
</ul>
<%= will_paginate %>

app/views/users/login.html.erb
<h1>Sign in</h1>

<%= form_for(:session, :url => sessions_path) do |f| %>

<%= form_for('sign in') do |f| %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Sign in" %>
  </div>
<% end %>

<p>New user? <%= link_to 'Sign Up', new_user_path(@user) %></p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= link_to 'Back', root_path %>
<%= render 'form' %>

app/views/users/show.html.erb
<table>
    <tr>
        <td>
            <% if @user.bookmarks.empty? %>
              <h4><i><strong>You haven't created any bookmarks yet. Get on it!</</strong></i></h4>
            <% else %>
                <table>
                    <h2 id='h2_header'>My Bookmarks</h2>
                        <%= render @bookmarks %>
                </table>
                <%= will_paginate @bookmarks %>
            <% end %>
        </td>
    </tr>
</table>
<%= link_to 'Create a New Bookmark', new_bookmark_path(@current_user) %>